apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: java-microservices
  namespace: flux-system
spec:
  interval: 1m
  url: http://git-server.flux-system/repo.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: java-microservices
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: services
  sourceRef:
    kind: GitRepository
    name: java-microservices
  path: "./"
  prune: true
  wait: true
