apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
  namespace: flux-system
  labels:
    app: git-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
      - name: git-server
        image: alpine/git
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache git-daemon nginx
          mkdir -p /git/repo.git
          cd /git/repo.git
          git init --bare
          git config --file config http.receivepack true
          git config --file config core.sharedRepository 0666
          
          # Configure Nginx
          mkdir -p /run/nginx
          echo "events {} http { server { listen 8080; root /git; location / { autoindex on; } } }" > /etc/nginx/nginx.conf
          
          # Start Nginx
          nginx -g "daemon off;"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: git-repo
          mountPath: /git
      volumes:
      - name: git-repo
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: flux-system
spec:
  selector:
    app: git-server
  ports:
  - port: 80
    targetPort: 8080
